CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    lastName VARCHAR(255) NOT NULL,
    birthDate VARCHAR(255) NOT NULL,
    identification VARCHAR(255) NOT NULL,
    profession VARCHAR(255) NOT NULL,
    monthlyIncome VARCHAR(255) NOT NULL,
    vehicle VARCHAR(255) NOT NULL,
    married BOOLEAN NOT NULL DEFAULT 0,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS vehicles (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    plate VARCHAR(255) NOT NULL,
    Brand VARCHAR(255) NOT NULL,
    model VARCHAR(255) NOT NULL,
    numberDoors INTEGER NOT NULL,
    vehicleType VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);